name: f_orm_m8_sqlite
description: Flutter package to generate SQLite fixture in conjuction with the package f_orm_m8.
version: 0.7.0+1
author: Mircea-Tiberiu MATEI<matei_tm@yahoo.com>
homepage: https://github.com/matei-tm/f-orm-m8-sqlite

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  build: '>=0.12.0 <2.0.0'
  analyzer: ^0.35.0
  path: ^1.6.2
  source_gen: ^0.9.0
  f_orm_m8: ^0.8.0

dev_dependencies:
  build_verify: ^1.1.0
  build_runner: ^1.0.0
  build_test: ^0.10.0
  source_gen_test: ^0.1.0
  test: ^1.3.3
